### ISSUE TITLE
Using the maven links

### ISSUE THREAD

**Issue by tyra314** [McJty/compatlayer#1]
I'd like to use this library, but I have trouble wrapping my mind around maven and gradle 🙊
Could you elaborate on how to use the links on the wiki page as maven repository?
Is it even possible to use them in gradle? Sorry, if this is a dumb question, but I'm pretty
new to Java.

What I tried so far, was adding it this way into my build.gradle:

```
repositories {
    maven { // CompatLayer
        url = "http://jenkins.k-4u.nl/view/McJty/job/Compatlayer%201.10/"
    }
}

dependencies {
    deobfCompile "mcjty.lib:compatlayer:1.10-0.0.12alpha"
}
```

**Comment by McJty** [comment]
I will add this soon. Planning a new big release of compatlayer which works for rftools

**Comment by McJty** [comment]
I updated the wiki with some information on how to setup the maven in build.gradle

**Comment by tyra314** [comment]
Works like a charm, thank you! 👍
