### ISSUE TITLE
Create CompatGUI(?)

### ISSUE THREAD

**Issue by EliteMasterEric** [McJty/compatlayer#12]
The field `GuiScreen#fontRendererObj` from 1.10.2 was renamed to `GuiScreen#fontRenderer` in 1.11. I'd like to have a class added for this.
The issue is that the commonly-used GuiContainer extends GuiScreen; would you have two compat classes, or is there some other solution?

**Comment by Landmaster** [comment]
They map to the same SRG name (which is what Forge uses internally), so a compatibility class should not be needed.
