### ISSUE TITLE
Constructor missing in 1.10 version only

### ISSUE THREAD

**Issue by zabi94** [McJty/compatlayer#16]
Whenever I try to initialize an ItemStackList(List\<ItemStack> stack, /\*Nullable*/ ItemStack defaultNullItem) on 1.10.2 version of CompatLayer I get

```
java.lang.NoSuchMethodError: mcjty.lib.tools.ItemStackList.<init>(Ljava/util/List;Lnet/minecraft/item/ItemStack;)V
```

On 1.11.2 this works just fine

Not sure if I should go a different way to get a custom ItemStackList, because add/set methods always crash minecraft super implemenatation

**Comment by McJty** [comment]
Can you show me the exact code you're using?

**Comment by zabi94** [comment]
``` java
@Override
public ItemStackList getRemainingItemsCompat(InventoryCrafting inv) {
	ArrayList<ItemStack> rem = new ArrayList<ItemStack>(inv.getSizeInventory());
	for (int i = 0; i < inv.getSizeInventory(); i++) {
		ItemStack is = inv.getStackInSlot(i);
		if (!ItemStackTools.isEmpty(is)) {
			if (!PotionUtils.getEffectsFromStack(is).isEmpty() && !is.getItem().equals(ItemSupporterMedal.INSTANCE)) {
				rem.add(is.copy());
			} else {
				rem.add(ItemStackTools.getEmptyStack());
			}
		} else {
			rem.add(ItemStackTools.getEmptyStack());
		}
	}
	return new ItemStackList(rem, ItemStackTools.getEmptyStack());
}
```

**Comment by McJty** [comment]
Hmm, that method was not intended to be public. You should probably avoid using it.

**Comment by zabi94** [comment]
How does one get an ItemStackList that is not filled with empty stacks then? add(...) and set(...) cannot be used, they throw UnsupportedOperationException

**Comment by McJty** [comment]
You can do:

    ItemStackList stacks = ItemStackList.create(9);

and then you can use stacks.set()

If you want a list where you can add items you do:

    ItemStackList stacks = ItemStackList.create();   (no parameter)

**Comment by zabi94** [comment]
Nope, you can't, that's the issue. The vanilla implementation of NonNullList\<E> always throws a UnsupportedOperationException when using _add_ and _set_

**Comment by McJty** [comment]
Yes but mine doesn't. I use it like that in rftools so it works fine

**Comment by zabi94** [comment]
Ok I swear to God eclipse/forge/minecraft is trying to make me go insane. 
Had it this way (set method was used) -> Run the game -> Crash with unsupported operation -> update and commit with hacky workaround -> no luck on 1.9.4 because of constructor -> roll back to the way it was in the begginning -> no crash 
Wtf. 
Eh, whatever. It works now
