### ISSUE TITLE
Can't add library to mod dependencies.

### ISSUE THREAD

**Issue by mainrs** [McJty/compatlayer#19]
I am fairly new to the whole modding thing. I wanted to add the compatlayer to the mod to make it compatible with 1.11 too. But as soon as I add the dependency within the `build.gradle` file,all minecraft and forge related dependencies get removed from the project. [Here](https://pastebin.com/EKpePnXz) is my `build.gradle` file. 
I invalidated the project several times and cleaned it too. No idea what is wrong.
I would really really appreciate any help since it is quite frustrating...

**Comment by Landmaster** [comment]
@SirWindfield On line 18, the "name" field is not needed. (In fact, McJty is spelled incorrectly on that line.) Did you remember to re-run `./gradlew setupDecompWorkspace` (and `./gradlew eclipse` if you are using Eclipse) again?

**Comment by mainrs** [comment]
oh, I have to rerun the commands? D:
**Edit:** Uh, it works. Thank you!
