### ISSUE TITLE
JEI compatability

### ISSUE THREAD

**Issue by chazwarp923** [McJty/compatlayer#2]
Would it be possible for you to make a compatlayer version of JEI's IIngredients?
During the port from 1.10-1.11 mezz made IIngredients.getInputs(Class<T> ingredientClass) return a list inside a list rather than just a list like in 1.10.

An example of this can be found [here](https://github.com/chazwarp923/Unified-Items/blob/3ece5d0131bd49c6b4a0b98b76aa0dd2089395fc/src/main/java/tech/chazwarp923/unifieditems/integration/jei/MortarAndPestleCategory.java).

The class in both versions, for reference.
[1.11](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/api/ingredients/IIngredients.java) [1.10](https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/api/ingredients/IIngredients.java)

**Comment by McJty** [comment]
???

The 1.10 version of getInputs() is returning a list of lists too. Just like in 1.11:

See:

https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/api/ingredients/IIngredients.java

	<T> List<List<T>> getInputs(Class<T> ingredientClass);

**Comment by chazwarp923** [comment]
Oops, I'm sorry, I was very tired when I wrote this up, I meant getOutputs()

**Comment by McJty** [comment]
Exactly how would you prefer to see this fixed?

**Comment by chazwarp923** [comment]
Well in 1.10 you could just return the normal result. But in 1.11 you'd need to simply perform a get function on the nested list. 
Something along the lines of `IIngredients.getOutputs(Class ingredientClass)` is implemented as normal in 1.10
But in 1.11 it'd be `IIngredients.getOutput(Class ingredientClass, Integer index)` and then you'd just add a `.get(index)` behind the scenes.

**Comment by McJty** [comment]
I'll add something

**Comment by chazwarp923** [comment]
Thanks a lot, and sorry for the trouble.

**Comment by McJty** [comment]
So I already added a class JeiCompatTools. What about:

**1.11 version:**

    public static <T> List<T> getOutputs(IIngredients ingredients, Class<T> clazz) {
        return ingredients.getOutputs(clazz).get(0);
    }

**1.10 version:**

    public static <T> List<T> getOutputs(IIngredients ingredients, Class<T> clazz) {
        return ingredients.getOutputs(clazz);
    }


Would that work for you?

**Comment by chazwarp923** [comment]
That should work just fine

**Comment by McJty** [comment]
Fixed in 0.2.1 which is already on maven. I will push a release later today but you can start using it already

**Comment by chazwarp923** [comment]
Thank you
