### ISSUE TITLE
Instant Crash with new version 0.3.1

### ISSUE THREAD

**Issue by Shivaxi** [McJty/compatlayer#27]
As soon as I start the game, I get an instant crash.  I am on Minecraft 1.11.2 and I also have Recurrent Complex which should be the only mod I have that relies on CompatLayer, so I assume it may have something to do with that.

Crashlog:  

[crash-2018-02-19_07.11.28-client.txt](https://github.com/McJty/compatlayer/files/1736704/crash-2018-02-19_07.11.28-client.txt)

**Comment by josephcsible** [comment]
Are you sure this is related to CompatLayer? I see nothing in the log that suggests it is. My top two guesses would be FoamFix or Tough as Nails.

**Comment by Shivaxi** [comment]
I tested again and now the crash doesn't happen using 0.3.1.  Very strange, considering it's the only mod I changed during the time of the crash.  I haven't touched TAN or FoamFix in months.  And I meant to say Lost Cities, not Recurrent Complex.  Lost Cities is why I have CompatLayer.

I guess this issue can be deleted then, sorry haha
