### ISSUE TITLE
Tile entity class?

### ISSUE THREAD

**Issue by IronworksProductions** [McJty/compatlayer#28]
I have a class that is a tile entity and implements Itickable. I've tried plugging in each of your classes but we run into a inconvertible error with one of the lines of code . None of your compat classes seem to handle tileentity's in the general scope and the code needs them to work.

Any ideas?

---
NN

**Comment by McJty** [comment]
Can you be more specific as to what you did and the errors you get? Also what version of MC

**Comment by IronworksProductions** [comment]
1.11
and here is the code snippet:
``` Java
public static SGBaseTE get(IBlockAccess world, BlockPos pos) {
        TileEntity te = world.getTileEntity(pos);
        if (te instanceof SGBaseTE)
            return (SGBaseTE)te;
```
I first replaced this:
```
public class SGBaseTE extends BaseTileInventory implements ITickable 
```
with
```
public class SGBaseTE extends EntityTools implements ITickable
```
when that did not work I tried worldtools and ended up leaving that there with the error. 
It says inconvertible types cannot cast net.minecraft.tileentity.TileEntity into gcewing.sg.SGBaseTE

**Comment by McJty** [comment]
Why are you extending EntityTools? That doesn't make sense. EntityTools is a class you should use. Don't extend from it. CompatLayer has nothing specific for TileEntities as they didn't really change between 1.10 and 1.11. Just use a normal TileEntity
