### ISSUE TITLE
Conflict with ye old tanks - coal causes crash

### ISSUE THREAD

**Issue by kzintiwife** [McJty/compatlayer#3]
When i place coal in the upper left  slot (1 or more - i tried both), the game crashes.  
i was trying to compress the coal into coal blocks. 
1. key press compression (from crafting tweaks) is okay
2. it doesnt matter what else is in the table or if it is empty. 

Ye' Olde tanks with JEI only, no crash
compat layer by itsself, no crash
starts crashing when compatlayer is added to Ye' Olde Tanks

here is the crash report. 

Link to crash report/log in a [gist](https://gist.github.com):

YeOldeTanks version: YeOldeTanks-1.11-1.9.2
Compatlayer version: compatlayer-1.11.2-0.2.1

Minecraft version: 1.11.2-forge1.11.2-13.20.0.2227, 1.11.2

[crash-2017-02-05_23.39.02-client.txt](https://github.com/McJty/compatlayer/files/753795/crash-2017-02-05_23.39.02-client.txt)

**Comment by McJty** [comment]
That can't be a bug in compatlayer as compatlayer does not do anything. It is just a library. Report this to YeOldeTanks instead
