### ISSUE TITLE
Create CompatSlotItemHandler

### ISSUE THREAD

**Issue by EliteMasterEric** [McJty/compatlayer#7]
I'd like to see a new class, mcjty.lib.compat.CompatSlotItemHandler, which extends net.minecraftforge.items.SlotItemHandler, and implements getX, getY, setX, setY, onTake, and onPickup for it.

I'm working with CompatLayer, and attempting to reimplement my class extending SlotItemHandler. However, I use onTake (which is not a method in 1.10.2) and to use CompatSlot I would have to re-implement all the logic in Forge's SlotItemHandler.

**Comment by McJty** [comment]
I can't find an onTake() in 1.11 either? What onTake do you mean?

**Comment by EliteMasterEric** [comment]
`net.minecraft.inventory.Slot#onTake(EntityPlayer thePlayer, ItemStack stack)`
I am on Forge 1.11.2-13-20.0.2252.

**Comment by McJty** [comment]
Sorry for the delay. Will try to deal with this later today if I find the time

**Comment by McJty** [comment]
Ok, working on this. Note that only onTake is needed as CompatSlot.getX also works on SlotItemHandler

**Comment by McJty** [comment]
Fixed next release (hopefully later)
