### ISSUE TITLE
Create CompatParticle

### ISSUE THREAD

**Issue by EliteMasterEric** [McJty/compatlayer#8]
I'd like to see a new class, mcjty.lib.compat.CompatParticle, which extends net.minecraft.client,particle.Particle, and creates overrides for getBoundingBox, getEntityBoundingBox, setBoundingBox, and setEntityBoundingBox.

During the change from 1.10.2 to 1.11.2, getEntityBoundingBox was renamed to getBoundingBox, and setEntityBoundingBox was renamed to setBoundingBox. Since boundingBox is private and cannot be accessed directly, and each pair of methods is identical other than their names, an implementation through CompatLayer would be perfect to resolve this problem.

**Comment by McJty** [comment]
Added CompatParticle. There is no new release yet but both this and the CompatSlotItemHandler can be gotten from maven so if you update to 0.2.3 in your build.gradle you should be able to use it already
