### ISSUE TITLE
Crash in dev with TheOneProbe + CompatLayer

### ISSUE THREAD

**Issue by MikeLydeamore** [McJty/compatlayer#9]
Trying to boot up in a dev environment and updated TOP to v1.1x-1.4.4-55
Had to add CompatLayer, v1.10-0.2.2

I'm crashing on world load with this:
http://pastebin.com/K3XELXx0

Any ideas?

**Comment by McJty** [comment]
Hmm, do you have recent mappings?

**Comment by MikeLydeamore** [comment]
My mappings are `stable_29`.

**Comment by McJty** [comment]
I'm not sure how old those are. I always try to use latest. I guess something has changed there.

**Comment by MikeLydeamore** [comment]
I'll try updating to the newest snapshot and test.

**Comment by MikeLydeamore** [comment]
So I'm getting an error on decompile with the latest 1.10.2 snapshot for some reason, but they were exported on the same day as the latest snapshot (http://export.mcpbot.bspk.rs/) which was several months after the ones used in compatlayer.

I do remember that (fairly) recently, things like `.worldObj` in TEs became `.world`, not sure if it's the same issue that may be flagging up here?

**Comment by mainrs** [comment]
> I do remember that (fairly) recently, things like .worldObj in TEs became .world, not sure if it's the same issue that may be flagging up here?

Using `getWorld()` instead of accessing the fields directly should solve problems like those I guess.

**Comment by josephcsible** [comment]
When you're using mods in dev, you should include their SRG-mapped jar via `deobfCompile` in gradle. This will automatically convert them to whatever MCP mappings your mod uses. Is that how you're including it? If not, what are you doing, and does that work?
